// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomePageDocumentDataSlicesSlice =
  | ExplanatorySectionSlice
  | FaqSectionSlice
  | HeroSectionSlice;

/**
 * Content for Home Page documents
 */
interface HomePageDocumentData {
  /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice> /**
   * Meta Title field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

type ProsePageDocumentDataSlicesSlice = ProseBlockSlice;

/**
 * Content for Prose Page documents
 */
interface ProsePageDocumentData {
  /**
   * Slice Zone field in *Prose Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: prose_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProsePageDocumentDataSlicesSlice> /**
   * Meta Title field in *Prose Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: prose_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Prose Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: prose_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Prose Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: prose_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Prose Page document from Prismic
 *
 * - **API ID**: `prose_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProsePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProsePageDocumentData>,
    "prose_page",
    Lang
  >;

export type AllDocumentTypes = HomePageDocument | ProsePageDocument;

/**
 * Primary content in *ExplanatorySection → Left Image → Primary*
 */
export interface ExplanatorySectionSliceDefaultPrimary {
  /**
   * Title field in *ExplanatorySection → Left Image → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Section title
   * - **API ID Path**: explanatory_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *ExplanatorySection → Left Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Section content with RTE
   * - **API ID Path**: explanatory_section.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Section Image field in *ExplanatorySection → Left Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: explanatory_section.default.primary.section_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  section_image: prismic.ImageField<never>;

  /**
   * Content Size field in *ExplanatorySection → Left Image → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select the content text size adjustment
   * - **Default Value**: default
   * - **API ID Path**: explanatory_section.default.primary.content_size
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  content_size: prismic.SelectField<"default" | "small" | "large", "filled">;

  /**
   * CTA Text field in *ExplanatorySection → Left Image → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Call-To-Action button label
   * - **API ID Path**: explanatory_section.default.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_text: prismic.Repeatable<prismic.LinkField>;
}

/**
 * Left Image variation for ExplanatorySection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExplanatorySectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ExplanatorySectionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ExplanatorySection → Right Image → Primary*
 */
export interface ExplanatorySectionSliceRightImagePrimary {
  /**
   * Title field in *ExplanatorySection → Right Image → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Section title
   * - **API ID Path**: explanatory_section.rightImage.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *ExplanatorySection → Right Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Section content with RTE
   * - **API ID Path**: explanatory_section.rightImage.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Section Image field in *ExplanatorySection → Right Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: explanatory_section.rightImage.primary.section_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  section_image: prismic.ImageField<never>;

  /**
   * Content Size field in *ExplanatorySection → Right Image → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select the content text size adjustment
   * - **Default Value**: default
   * - **API ID Path**: explanatory_section.rightImage.primary.content_size
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  content_size: prismic.SelectField<"default" | "small" | "large", "filled">;

  /**
   * CTA Text field in *ExplanatorySection → Right Image → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Call-To-Action button label
   * - **API ID Path**: explanatory_section.rightImage.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_text: prismic.Repeatable<prismic.LinkField>;
}

/**
 * Right Image variation for ExplanatorySection Slice
 *
 * - **API ID**: `rightImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExplanatorySectionSliceRightImage = prismic.SharedSliceVariation<
  "rightImage",
  Simplify<ExplanatorySectionSliceRightImagePrimary>,
  never
>;

/**
 * Primary content in *ExplanatorySection → Centered → Primary*
 */
export interface ExplanatorySectionSliceCenteredPrimary {
  /**
   * Title field in *ExplanatorySection → Centered → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Section title
   * - **API ID Path**: explanatory_section.centered.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *ExplanatorySection → Centered → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Section content with RTE
   * - **API ID Path**: explanatory_section.centered.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Section Image field in *ExplanatorySection → Centered → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: explanatory_section.centered.primary.section_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  section_image: prismic.ImageField<never>;

  /**
   * Content Size field in *ExplanatorySection → Centered → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select the content text size adjustment
   * - **Default Value**: default
   * - **API ID Path**: explanatory_section.centered.primary.content_size
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  content_size: prismic.SelectField<"default" | "small" | "large", "filled">;

  /**
   * CTA Text field in *ExplanatorySection → Centered → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Call-To-Action button label
   * - **API ID Path**: explanatory_section.centered.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_text: prismic.Repeatable<prismic.LinkField>;
}

/**
 * Centered variation for ExplanatorySection Slice
 *
 * - **API ID**: `centered`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExplanatorySectionSliceCentered = prismic.SharedSliceVariation<
  "centered",
  Simplify<ExplanatorySectionSliceCenteredPrimary>,
  never
>;

/**
 * Slice variation for *ExplanatorySection*
 */
type ExplanatorySectionSliceVariation =
  | ExplanatorySectionSliceDefault
  | ExplanatorySectionSliceRightImage
  | ExplanatorySectionSliceCentered;

/**
 * ExplanatorySection Shared Slice
 *
 * - **API ID**: `explanatory_section`
 * - **Description**: ExplanatorySection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExplanatorySectionSlice = prismic.SharedSlice<
  "explanatory_section",
  ExplanatorySectionSliceVariation
>;

/**
 * Item in *FaqSection → Default → Primary → Disclosure*
 */
export interface FaqSectionSliceDefaultPrimaryDisclosureItem {
  /**
   * Title field in *FaqSection → Default → Primary → Disclosure*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Disclosure Title
   * - **API ID Path**: faq_section.default.primary.disclosure[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *FaqSection → Default → Primary → Disclosure*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Disclosure Rich Text Content
   * - **API ID Path**: faq_section.default.primary.disclosure[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Primary content in *FaqSection → Default → Primary*
 */
export interface FaqSectionSliceDefaultPrimary {
  /**
   * Section Title field in *FaqSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_title: prismic.KeyTextField;

  /**
   * Section Description field in *FaqSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.default.primary.section_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_description: prismic.RichTextField;

  /**
   * Disclosure field in *FaqSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.default.primary.disclosure[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  disclosure: prismic.GroupField<
    Simplify<FaqSectionSliceDefaultPrimaryDisclosureItem>
  >;
}

/**
 * Default variation for FaqSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FaqSection*
 */
type FaqSectionSliceVariation = FaqSectionSliceDefault;

/**
 * FaqSection Shared Slice
 *
 * - **API ID**: `faq_section`
 * - **Description**: FaqSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSectionSlice = prismic.SharedSlice<
  "faq_section",
  FaqSectionSliceVariation
>;

/**
 * Primary content in *HeroSection → Default → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * Title field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Hero section title for <h1>
   * - **API ID Path**: hero_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Hero section description
   * - **API ID Path**: hero_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * CTA Text field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Call-To-Action button label
   * - **API ID Path**: hero_section.default.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_text: prismic.KeyTextField;
}

/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *HeroSection → With BG Image → Primary*
 */
export interface HeroSectionSliceWithBgImagePrimary {
  /**
   * Title field in *HeroSection → With BG Image → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Hero section title for <h1>
   * - **API ID Path**: hero_section.withBgImage.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *HeroSection → With BG Image → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Hero section description
   * - **API ID Path**: hero_section.withBgImage.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * CTA Text field in *HeroSection → With BG Image → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Call-To-Action button label
   * - **API ID Path**: hero_section.withBgImage.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_text: prismic.KeyTextField;

  /**
   * Background Image field in *HeroSection → With BG Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.withBgImage.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * With BG Image variation for HeroSection Slice
 *
 * - **API ID**: `withBgImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSliceWithBgImage = prismic.SharedSliceVariation<
  "withBgImage",
  Simplify<HeroSectionSliceWithBgImagePrimary>,
  never
>;

/**
 * Slice variation for *HeroSection*
 */
type HeroSectionSliceVariation =
  | HeroSectionSliceDefault
  | HeroSectionSliceWithBgImage;

/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: HeroSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

/**
 * Primary content in *ProseSection → Default → Primary*
 */
export interface ProseBlockSliceDefaultPrimary {
  /**
   * Title field in *ProseSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Prose title for the page or post
   * - **API ID Path**: prose_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *ProseSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Prose description for the page or post (optional)
   * - **API ID Path**: prose_block.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Content field in *ProseSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Page content
   * - **API ID Path**: prose_block.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for ProseSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProseBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProseBlockSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ProseSection → Legal → Primary*
 */
export interface ProseBlockSliceLegalPrimary {
  /**
   * Title field in *ProseSection → Legal → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Prose title for the page or post
   * - **API ID Path**: prose_block.legal.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *ProseSection → Legal → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Prose description for the page or post (optional)
   * - **API ID Path**: prose_block.legal.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Content field in *ProseSection → Legal → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Page content
   * - **API ID Path**: prose_block.legal.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Effective Date field in *ProseSection → Legal → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: prose_block.legal.primary.effective_date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  effective_date: prismic.DateField;
}

/**
 * Legal variation for ProseSection Slice
 *
 * - **API ID**: `legal`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProseBlockSliceLegal = prismic.SharedSliceVariation<
  "legal",
  Simplify<ProseBlockSliceLegalPrimary>,
  never
>;

/**
 * Slice variation for *ProseSection*
 */
type ProseBlockSliceVariation = ProseBlockSliceDefault | ProseBlockSliceLegal;

/**
 * ProseSection Shared Slice
 *
 * - **API ID**: `prose_block`
 * - **Description**: ProseBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProseBlockSlice = prismic.SharedSlice<
  "prose_block",
  ProseBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      ProsePageDocument,
      ProsePageDocumentData,
      ProsePageDocumentDataSlicesSlice,
      AllDocumentTypes,
      ExplanatorySectionSlice,
      ExplanatorySectionSliceDefaultPrimary,
      ExplanatorySectionSliceRightImagePrimary,
      ExplanatorySectionSliceCenteredPrimary,
      ExplanatorySectionSliceVariation,
      ExplanatorySectionSliceDefault,
      ExplanatorySectionSliceRightImage,
      ExplanatorySectionSliceCentered,
      FaqSectionSlice,
      FaqSectionSliceDefaultPrimaryDisclosureItem,
      FaqSectionSliceDefaultPrimary,
      FaqSectionSliceVariation,
      FaqSectionSliceDefault,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceWithBgImagePrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      HeroSectionSliceWithBgImage,
      ProseBlockSlice,
      ProseBlockSliceDefaultPrimary,
      ProseBlockSliceLegalPrimary,
      ProseBlockSliceVariation,
      ProseBlockSliceDefault,
      ProseBlockSliceLegal,
    };
  }
}
