// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  hero_section: defineAsyncComponent(() => import("./HeroSection/index.vue")),
  prose_block: defineAsyncComponent(() => import("./ProseSection/index.vue")),
});
