// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  explanatory_section: defineAsyncComponent(
    () => import("./ExplanatorySection/index.vue")
  ),
  faq_section: defineAsyncComponent(() => import("./FaqSection/index.vue")),
  hero_section: defineAsyncComponent(() => import("./HeroSection/index.vue")),
  prose_block: defineAsyncComponent(() => import("./ProseSection/index.vue")),
});
